### ISSUE TITLE
Add the ability to toggle all modules

### ISSUE THREAD

**Issue by JosTheDude** [smuddgge/SmUtility#1]
I'd like to toggle the modules of the plugin (ex. Staff Chat, Reports, Etc.) so it'd be nice to have a toggling feature in the config to do so, since some people might only need a few things from SMUtility, so being able to toggle what you want could help server owners & managers better clean up their server's proxy command list :)

Noticed you added the 1.19 Chat toggle for Staff Chats, awesome :D

**Comment by Smudgge** [comment]
Thank you for suggesting this feature, I've implemented this in the next version :3
