### ISSUE TITLE
Send Command Arguement Issues

### ISSUE THREAD

**Issue by JosTheDude** [smuddgge/SmUtility#5]
When using /send without any arguements, it throws a NullPointerException & the send command usage is a tad bit weird (`/send [ign] #[server-name]` so it's a bit confusing for new users transferring for velocity

**Comment by Smudgge** [comment]
Hey @JosTheDude, sorry for the long wait. Ill include this in the new utility plugin I'm developing called leaf. Thanks for all the feedback ❤️

**Comment by JosTheDude** [comment]
Oh okay! I was wondering if you had a discord btw that I could friend you on c:

> Hey @JosTheDude, sorry for the long wait. Ill include this in the new utility plugin I'm developing called leaf. Thanks for all the feedback ❤️

**Comment by Smudgge** [comment]
For sure! Ive just linked my discord server in my profile if you would like to join :3 
https://github.com/smuddgge

**Comment by Smudgge** [comment]
Ill close this ticket as ill add it in the new plugin
